### ISSUE TITLE
DataArray not defined

### ISSUE THREAD

**Issue by chengrunyang** [JackDunnNZ/UCIData.jl#11]
I tried to run `julia runconvert.jl -m` in Julia v0.6.2 and encountered the following error:

```
ERROR: LoadError: LoadError: UndefVarError: DataArray not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:305
 [6] _start() at ./client.jl:371
while loading /Users/craig/Downloads/uci-data-master/convert.jl, in expression starting on line 29
while loading /Users/craig/Downloads/uci-data-master/runconvert.jl, in expression starting on line 3
```

It seems installing `DataArrays.jl` doesn't help. Any suggestions? Thanks!

**Comment by JackDunnNZ** [comment]
I think the problem is that the newer version of DataFrames.jl doesn't use DataArrays, so for this code to work you will need to either update the code to use whatever DataFrames uses now, or use a version of DataFrames prior to 0.11 which is where the change happened.

**Comment by chengrunyang** [comment]
Problem solved, thanks!

A note to future users: pinning `DataFrames.jl` to an earlier version (I used v0.10.0) does help, by doing
```
Pkg.add("DataFrames.jl")
Pkg.pin("DataFrames.jl", v"0.10.0")
```
