### ISSUE TITLE
Config.ini file of soybean-large

### ISSUE THREAD

**Issue by chengrunyang** [JackDunnNZ/UCIData.jl#13]
Looks like [`config.ini`](https://github.com/JackDunnNZ/uci-data/blob/master/datafiles/classification/soybean-large/config.ini) of the soybean-large dataset might need to be modified: `value_indices` and `categoric_indices` should range from 1 to 35, while `target_index` should be 36; these are consistent with http://archive.ics.uci.edu/ml/datasets/Soybean+%28Large%29 and the converted .data file.

**Comment by JackDunnNZ** [comment]
When I look at the datafile (https://archive.ics.uci.edu/ml/machine-learning-databases/soybean/soybean-large.data) I see the target class as the first column. Am I missing something?

**Comment by chengrunyang** [comment]
Oh, you are right. The mismatch I mentioned was between `config.ini` and the converted `.data` files. 

Is there an annotation file I can refer to for the properties of columns in `.data` (i.e. whether each column is categorical feature, numerical feature or the target class label)?

**Comment by JackDunnNZ** [comment]
The structure of .data is that the first column is an ID, the last column
is the target, and everything else is a feature. The categoric features are
written as strings in the file and the numeric are numbers

**Comment by chengrunyang** [comment]
OK, thanks!
