### ISSUE TITLE
Any criteria for the selection of UCI datasets?

### ISSUE THREAD

**Issue by chengrunyang** [JackDunnNZ/UCIData.jl#15]
Hi, I wonder if the UCI datasets documented here are chosen at random, or if you have some criteria for that.

Thanks!

**Comment by JackDunnNZ** [comment]
There's no real criteria, these were just the datasets that were the easiest to process, as they were already in a sensible-ish format to begin with so easy to handle with a generic processing script :)

**Comment by chengrunyang** [comment]
Aha, thanks for the quick reply! I may add some more config files at some point.
