### ISSUE TITLE
Fail to proceed 'julia runconvert.jl'

### ISSUE THREAD

**Issue by Hrj9499** [JackDunnNZ/UCIData.jl#18]
This is very naive question as it's my first using Julia...

I download the uci-data-master and run it in Atom. I get the ParseError after proceeding 'julia runconvert.jl'. I have installed all the packages required. 

Detail is in the attached photo... Thanks if you may have a look
![screenshot](https://user-images.githubusercontent.com/40732276/42732953-29f931c2-885d-11e8-9a01-e08c88e42bdd.png)

**Comment by JackDunnNZ** [comment]
`julia runconvert.jl` is meant to be run from the command line, not from inside Julia itself. If you would like to run from inside Julia, you could do this with

```julia
include("convert.jl")
keepcat = true # or false
keepna = true # or false
processalldirs("classification", keepcat, keepna)
processalldirs("regression", keepcat, keepna)
```

**Comment by Hrj9499** [comment]
Thank you Jack. Problem is solved!

Btw DataFrames doest not support DataArrays anymore.
Need to Pkg.add("DataArrays") and code in 'using DataArrays' in converter.jl
