### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by colin78** [JackDunnNZ/UCIData.jl#3]
Hey Jack,

I hope that your summer is going well!  I just tried running this package in Julia 0.6, and there were several dependencies I had to install:

Pkg.add("ArgParse")
Pkg.add("ConfParser")
Pkg.add("DataFrames")
Pkg.add("Combinatorics")
Pkg.add("ZipFile")
Pkg.add("LegacyStrings")
Pkg.add("EnglishText")

Just thought that you should know if you want to add this to the documentation.

Best,
Colin

**Comment by JackDunnNZ** [comment]
You should make a pull request to add to the documentation!

**Comment by Hrj9499** [comment]
DataArray is nolonger in DataFrame package. 
An extra Pkg.add("DataArrays") is required.

**Comment by JackDunnNZ** [comment]
Fixed by #19
