### ISSUE TITLE
legacystrings -> transcode?

### ISSUE THREAD

**Issue by stevengj** [JackDunnNZ/UCIData.jl#34]
Interestingly, this is currently the only registered Julia package that uses LegacyStrings, so I was curious as to why you needed it.  It looks like the only way you use it is for the `utf16` function, e.g. [here](https://github.com/JackDunnNZ/UCIData.jl/blob/5106b603fd4e6309def1af4d37cf8ebd407e7643/src/data/classification/acute-inflammations-2.jl)
```jl
data = LegacyStrings.utf16(read(path)[3:end])
data = replace(data, "," => ".")
write(path, data)
```
But if you just want to convert bytes (UTF-8?) to UTF-16, you can use the [`transcode` function in `Base`](https://docs.julialang.org/en/v1/base/strings/#Base.transcode), e.g.
```jl
bytes = read(path)[3:end]
replace!(bytes, UInt8(',') => UInt8('.'))
data = transcode(UInt16, bytes) # convert to UTF-16
write(path, data)
```

**Comment by JackDunnNZ** [comment]
Thanks for pointing this out. I think this is just really old and was just never changed after `utf16` was deprecated and removed from Base. #35 removes this and uses `transcode` instead (albeit in reverse to go from UTF-16 to a string)
